GET https://tools.ecpe.nu.ac.th/network/api/students
Content-Type: application/x-www-form-urlcoded
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC90b29scy5lY3BlLm51LmFjLnRoXC9uZXR3b3JrXC9hcGlcL2xvZ2luIiwiaWF0IjoxNjU4NzQ5MjMzLCJleHAiOjE2NTg3NTI4MzMsIm5iZiI6MTY1ODc0OTIzMywianRpIjoiT2JDQ1ZMbno4RUxHY2xXRiIsInN1YiI6MSwicHJ2IjoiMjNiZDVjODk0OWY2MDBhZGIzOWU3MDFjNDAwODcyZGI3YTU5NzZmNyJ9.gSoTKn7xjrIblaapWe8DDbsGo7VUVm0tcUILgRf0nG0
Accept: application/json
