GET https://tools.ecpe.nu.ac.th/network/api/student/63365862 HTTP/1.1
Content-Type: application/x-www-form-urlcoded
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC90b29scy5lY3BlLm51LmFjLnRoXC9uZXR3b3JrXC9hcGlcL2xvZ2luIiwiaWF0IjoxNjU4NzQzOTA3LCJleHAiOjE2NTg3NDc1MDcsIm5iZiI6MTY1ODc0MzkwNywianRpIjoiNFZXRlhoYjNwV0FqWlh3TSIsInN1YiI6MSwicHJ2IjoiMjNiZDVjODk0OWY2MDBhZGIzOWU3MDFjNDAwODcyZGI3YTU5NzZmNyJ9.W0glBvUAmflyD32PM7iHtSL9zk1ct0eAWYVWKOkjRJQ
Accept: application/json