GET http://localhost:8000/api/students
Content-Type: application/x-www-form-urlcoded
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6ODAwMFwvYXBpXC9sb2dpbiIsImlhdCI6MTY1OTIzNzgxNCwiZXhwIjoxNjU5MjQxNDE0LCJuYmYiOjE2NTkyMzc4MTQsImp0aSI6IlNkMFZhbjliVXdxR1gycHkiLCJzdWIiOjIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.wITlzoM3vSfEd0VFwe-lUmZxmYiXnZ3BglUEqcaRMTw
Accept: application/json
